# Generated by Django 5.1.1 on 2024-10-30 00:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtsNearMe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteevent',
            unique_together={('user', 'event_id')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteplace',
            unique_together={('user', 'place_id')},
        ),
    ]
