# Generated by Django 4.2 on 2024-10-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtsNearMe', '0002_favoriteplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_start_time', models.CharField(max_length=255)),
                ('place_website', models.URLField(blank=True, null=True)),
                ('place_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtsNearMe.user')),
            ],
        ),
    ]
