# Generated by Django 5.1.1 on 2024-10-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtsNearMe', '0002_alter_favoriteevent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteevent',
            name='event_id',
            field=models.CharField(max_length=100),
        ),
    ]
