# Generated by Django 5.1.1 on 2024-10-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtsNearMe', '0003_favoriteevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteevent',
            old_name='place_id',
            new_name='event_id',
        ),
    ]
