# Generated by Django 5.1.1 on 2024-10-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtsNearMe', '0005_alter_favoriteevent_user_alter_favoriteplace_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
